ARG VERSION="20"
FROM mcr.microsoft.com/devcontainers/javascript-node:1-${VERSION}

# RUN apt-get update && \
#   export DEBIAN_FRONTEND=noninteractive && \
#   apt-get install -y --no-install-recommends

# using corepack to manage yarn version
RUN corepack enable